<ClockScreen>:
	time_label: time_label
	alarm_label: alarm_label
	orientation: "vertical"
	padding: 20
	canvas.before:
		Color:
			rgba: self.background_color
		Rectangle:
			size: self.size
			pos: self.pos	

	Label:
		id: time_label
		bold: True
		font_size: "250sp"
		color: root.time_label_color
		size_hint_y: 1.8

	Label:
		id: alarm_label
		color: root.alarm_label_color
		font_size: "30sp"

ClockScreen					